apiVersion: extensions/v1beta1
kind: Job
metadata:
  name: storm-examples
spec:
  selector:
    matchLabels:
      app: storm-examples
  template:
    metadata:
      name: storm-examples
      labels:
        app: storm-examples
    spec:
      containers:
      - name: storm-examples
        image: adejonge/storm-examples
      restartPolicy: Never
