apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  ports:
    - name: name1
      port: 2181
      targetPort: 2181
    - name: name2
      port: 2888
      targetPort: 2888
    - name: name3
      port: 3888
      targetPort: 3888
  selector:
    app: zookeeper
